# Generated by Django 3.2.20 on 2023-09-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que', models.CharField(max_length=300)),
                ('a', models.CharField(max_length=300)),
                ('b', models.CharField(max_length=300)),
                ('c', models.CharField(max_length=300)),
                ('d', models.CharField(max_length=300)),
                ('ans', models.CharField(max_length=300)),
            ],
        ),
    ]
